name: score_rosario
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  add_2_calendar: ^3.0.1
  change_app_package_name: ^1.4.0
  cupertino_icons: ^1.0.8
  device_calendar: ^4.3.3
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  go_router: ^14.8.0
  onesignal_flutter: ^5.2.9
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.18.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/fucsia.png
    - assets/images/orange.png
    - assets/images/pink.png
    - assets/images/purple.png
    - assets/images/logo.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/mobile.png
    - assets/images/logonegro.png
    - assets/images/rosario.jpg
    - assets/images/logo_urosario.png
    - assets/images/indices.jpeg
    - assets/images/calendar.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_urosario.png"

flutter_native_splash:
  color: "#7FBFAA"
  image: "assets/images/logo_score.jpg"
